use std::error::Error;
use std::fs;
use std::path::PathBuf;

use asm_aut::AnalysisReport;
use asm_gauge::ClosureOpts;
use asm_gauge::{analyze_gauge, build_rep, to_canonical_json_bytes, GaugeOpts, RepOpts, WardOpts};
use asm_spec::{from_json_slice as spectrum_from_slice, SpectrumReport};
use clap::Args;

#[derive(Args, Debug)]
pub struct GaugeArgs {
    /// Spectrum report generated by `asm-sim spectrum`.
    #[arg(long)]
    pub spectrum: PathBuf,
    /// Automorphism analysis report generated by `asm-aut`.
    #[arg(long)]
    pub aut: PathBuf,
    /// Output directory for gauge artefacts.
    #[arg(long)]
    pub out: PathBuf,
    /// Maximum number of representation generators to retain.
    #[arg(long, default_value_t = 3)]
    pub max_generators: usize,
    /// Closure tolerance recorded in the report.
    #[arg(long, default_value_t = 1e-6)]
    pub closure_tol: f64,
    /// Ward relative tolerance recorded in the report.
    #[arg(long, default_value_t = 1e-5)]
    pub ward_tol: f64,
    /// Optional deterministic seed overriding provenance defaults.
    #[arg(long, default_value_t = 0)]
    pub seed: u64,
}

fn load_spectrum(path: &PathBuf) -> Result<SpectrumReport, Box<dyn Error>> {
    let bytes = fs::read(path)?;
    Ok(spectrum_from_slice(&bytes)?)
}

fn load_analysis(path: &PathBuf) -> Result<AnalysisReport, Box<dyn Error>> {
    let json = fs::read_to_string(path)?;
    Ok(serde_json::from_str(&json)?)
}

pub fn run(args: &GaugeArgs) -> Result<(), Box<dyn Error>> {
    fs::create_dir_all(&args.out)?;
    let spectrum = load_spectrum(&args.spectrum)?;
    let analysis = load_analysis(&args.aut)?;

    let mut rep_opts = RepOpts::default();
    rep_opts.max_generators = args.max_generators.max(1);
    if args.seed != 0 {
        rep_opts.seed = Some(args.seed);
    }
    let closure_opts = ClosureOpts {
        tolerance: args.closure_tol,
    };
    let ward_opts = WardOpts {
        relative_tol: args.ward_tol,
    };
    let gauge_opts = GaugeOpts {
        rep: rep_opts.clone(),
        closure: closure_opts.clone(),
        ward: ward_opts.clone(),
        seed: args.seed,
        ..GaugeOpts::default()
    };

    let rep = build_rep(&spectrum, &analysis, &rep_opts)?;
    let report = analyze_gauge(&spectrum, &analysis, &spectrum.operators.info, &gauge_opts)?;

    fs::write(args.out.join("rep.json"), to_canonical_json_bytes(&rep)?)?;
    fs::write(
        args.out.join("closure.json"),
        to_canonical_json_bytes(&report.closure)?,
    )?;
    fs::write(
        args.out.join("decomp.json"),
        to_canonical_json_bytes(&report.decomp)?,
    )?;
    fs::write(
        args.out.join("ward.json"),
        to_canonical_json_bytes(&report.ward)?,
    )?;
    fs::write(
        args.out.join("gauge_report.json"),
        to_canonical_json_bytes(&report)?,
    )?;

    Ok(())
}
